### ISSUE TITLE
Feature request pypi

### ISSUE THREAD

**Issue by kennedyshead** [spaam/swedbank-cli#9]
Is it ok if I fix this to be packaged for pypi?
I also would like to adjust it so it can be used as a lib rather than cli.

If its not in your interest can I base a new lib with some borrowing from your code?

**Comment by spaam** [comment]
sure it sounds good if you want to do that. i can fix so you have commit rights to my repo :)

**Comment by kennedyshead** [comment]
Thank you :) I will see what I can do as soon as I have a moment.

**Comment by spaam** [comment]
you have the permissions now to commit and change stuff :)

**Comment by kennedyshead** [comment]
FYI I am doing it to make it work with https://github.com/balloob/home-assistant :)

**Comment by spaam** [comment]
oh never heard about it. looks cool :)

**Comment by kennedyshead** [comment]
Merged in #12
